"""Loading the two public catalogues used in the numerical study.

Both are distributed with the CASdatasets R package, mirrored on GitHub at
https://github.com/dutangc/CASdatasets (clone once; see README).

  FedYieldCurve : monthly US Treasury constant-maturity yields, 8 maturities.
  auscathist    : normalised Australian catastrophe event losses, 1967-2014.
"""
from __future__ import annotations

import numpy as np

MATURITIES = ["R_3M", "R_6M", "R_1Y", "R_2Y", "R_3Y", "R_5Y", "R_7Y", "R_10Y"]
KEY_RATE_DURATIONS = np.array([0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0])
PERILS = ["Storm", "Cyclone", "Hailstorm", "Bushfire", "Flood"]


def _read_rda(path: str, name: str):
    import pyreadr
    return pyreadr.read_r(path)[name]


def yield_changes(casdatasets_dir: str) -> np.ndarray:
    """371 monthly changes in 8 key rates.  Rows are observations.

    The eight key-rate columns are selected explicitly.  Differencing the frame
    wholesale would pull in any non-rate column (a date field, for instance) and
    either fail the float cast or contribute a spurious ninth factor, silently
    contradicting the d = 8 used throughout the paper.
    """
    Y = _read_rda(f"{casdatasets_dir}/data/FedYieldCurve.rda", "FedYieldCurve")
    missing = [c for c in MATURITIES if c not in Y.columns]
    if missing:
        raise KeyError(f"FedYieldCurve is missing key-rate columns: {missing}")
    dY = np.diff(Y[MATURITIES].values.astype(float), axis=0)
    dY = dY[~np.isnan(dY).any(axis=1)]
    if dY.shape != (371, 8):
        raise ValueError(
            f"expected 371 monthly changes in 8 key rates, got {dY.shape}; "
            "the paper's design assumes 372 observations of 8 maturities")
    return dY


def block_bootstrap(x: np.ndarray, n: int, seed: int, block: int = 6
                    ) -> np.ndarray:
    """Centred moving-block bootstrap, preserving short-range dependence."""
    rng = np.random.default_rng(seed)
    # Upper limit is exclusive, so the admissible starts are 0 .. len(x)-block
    # inclusive; omitting the +1 would leave the final observation of the series
    # unreachable by any block.
    starts = rng.integers(0, len(x) - block + 1, size=n // block + 1)
    out = np.concatenate([x[s:s + block] for s in starts])[:n]
    return out - out.mean(axis=0)


def annual_peril_aggregates(casdatasets_dir: str) -> np.ndarray:
    """48 annual aggregate losses per peril (5 perils), 1967-2014."""
    import pandas as pd  # noqa: F401  (pyreadr returns a DataFrame)
    A = _read_rda(f"{casdatasets_dir}/data/auscathist.rda", "auscathist")
    A = A[["Year", "Type", "NormCost2014"]].dropna()
    A["NormCost2014"] = A["NormCost2014"].astype(float)
    A = A[A.Type.isin(PERILS)]
    years = np.arange(int(A.Year.min()), int(A.Year.max()) + 1)
    agg = np.zeros((len(years), len(PERILS)))
    for i, y in enumerate(years):
        sub = A[A.Year == y]
        for j, p in enumerate(PERILS):
            agg[i, j] = sub[sub.Type == p]["NormCost2014"].sum()
    return agg


def fit_and_simulate(agg: np.ndarray, rng, n: int):
    """Zero-inflated lognormal marginals with a Gaussian copula on log scale.

    Returns (centred catalogue, fitted log-scale correlation matrix).  Shared by
    the catastrophe experiments so the reference catalogue and the bootstrap
    replicates are generated by one implementation.
    """
    d = agg.shape[1]
    lam = (agg > 0).mean(axis=0)
    mu_, sd_ = np.zeros(d), np.zeros(d)
    for j in range(d):
        pos = agg[agg[:, j] > 0, j]
        if len(pos) < 2:
            mu_[j] = np.log(max(pos.mean(), 1.0)) if len(pos) else 0.0
            sd_[j] = 1.0
        else:
            mu_[j], sd_[j] = np.log(pos).mean(), max(np.log(pos).std(), 1e-3)

    C = np.nan_to_num(np.corrcoef(np.log1p(agg).T), nan=0.0)
    np.fill_diagonal(C, 1.0)
    ev, evec = np.linalg.eigh(C)                       # nearest-PSD repair
    C = evec @ np.diag(np.maximum(ev, 1e-6)) @ evec.T
    dg = np.sqrt(np.diag(C)); C = C / np.outer(dg, dg)

    L = np.linalg.cholesky(C + 1e-9 * np.eye(d))
    Z = rng.normal(size=(n, d)) @ L.T
    F = np.exp(mu_ + sd_ * Z) * (rng.random((n, d)) < lam) / 1000.0
    return F - F.mean(axis=0), C


def catastrophe_catalogue(casdatasets_dir: str, n: int = 40_000, seed: int = 1):
    """Simulated multi-peril catalogue at the design of the main numerical study."""
    agg = annual_peril_aggregates(casdatasets_dir)
    return fit_and_simulate(agg, np.random.default_rng(seed), n)


# --------------------------------------------------------------------------
# synthetic calibration population
# --------------------------------------------------------------------------

#: Principal-component variance shares of the synthetic factor covariance,
#: reproducing the Treasury cumulative shares 0.861/0.975/0.990/0.996 at ranks
#: one to four, with lambda_1/lambda_2 = 7.5.  The remaining mass is spread over
#: the trailing components.
PC_SHARES = (0.861, 0.114, 0.015, 0.006)


def synthetic_covariance(d: int = 8, seed: int = 0) -> np.ndarray:
    """Factor covariance with the calibrated principal-component shares.

    The leading four eigenvalues are PC_SHARES; the remainder (0.004) is spread
    geometrically over the trailing d-4 components, so the spectrum decays
    rather than ending in a flat plateau.  Eigenvectors are a Haar-random
    orthogonal basis, which fixes the spectrum without privileging any
    coordinate direction.
    """
    if d < len(PC_SHARES) + 1:
        raise ValueError(f"d must exceed {len(PC_SHARES)}")
    tail_n = d - len(PC_SHARES)
    tail = 0.5 ** np.arange(1, tail_n + 1)
    tail = tail / tail.sum() * (1.0 - sum(PC_SHARES))
    lam = np.concatenate([np.array(PC_SHARES), tail])

    # Eigenvectors are the level/slope/curvature shapes of a real yield curve,
    # obtained by orthonormalising polynomials in log maturity.  Calibrating the
    # eigenvalues alone is not enough: gamma_j(U) measures the alignment between
    # the retained subspace and the candidates' duration slopes, and a
    # Haar-random basis destroys that alignment (a duration vector projects onto
    # a random first component at roughly a quarter of the strength it projects
    # onto a level factor), which shifts every certified fraction.
    dur = KEY_RATE_DURATIONS if d == len(KEY_RATE_DURATIONS) else \
        np.geomspace(0.25, 10.0, d)
    x = np.log(dur) - np.log(dur).mean()
    x = x / np.abs(x).max()
    Q, _ = np.linalg.qr(np.vander(x, d, increasing=True))
    return (Q * lam) @ Q.T


def synthetic_catalogue(n: int = 40_000, seed: int = 0, d: int = 8,
                        df: int = 6) -> np.ndarray:
    """Student-t catalogue with the calibrated second-order structure.

    Innovations are Student-t with `df` degrees of freedom, standardised to unit
    variance and coloured by the Cholesky factor of the synthetic covariance, so
    the catalogue is heavier-tailed than Gaussian while matching the target
    second-order structure.  Centred before return.
    """
    rng = np.random.default_rng(seed)
    L = np.linalg.cholesky(synthetic_covariance(d, seed=seed))
    t = rng.standard_t(df, size=(n, d))
    t /= np.sqrt(df / (df - 2.0))                  # unit variance
    F = t @ L.T
    return F - F.mean(axis=0)
