"""Candidate-population generators.

Both populations are subsets of a shared exposure pool, which is what makes
them sparse and heterogeneous in their alignment with the retained subspace --
the structural condition under which certification is effective: populations
generated by combinatorial search are sparse and heterogeneous in their alignment
with the retained subspace, whereas a homogeneous population is the adverse case.
"""
from __future__ import annotations

import numpy as np

from .certificate import Candidate
from .data import KEY_RATE_DURATIONS


def bond_books(n_candidates: int, m: int, K: int, seed: int, d: int = 8,
               live_prob: float = 0.75) -> list[Candidate]:
    """Bond books holding `m` of `d` maturities, with K embedded-floor regimes.

    Slopes are key-rate duration vectors supported on the held maturities.
    """
    rng = np.random.default_rng(seed)
    out = []
    for _ in range(n_candidates):
        S = rng.choice(d, size=m, replace=False)
        w = rng.exponential(size=m); w /= w.sum()
        base = np.zeros(d); base[S] = -w * KEY_RATE_DURATIONS[S] * 100.0
        b = np.zeros((K, d))
        for t in range(K):
            keep = rng.random(m) < live_prob
            v = np.zeros(d); v[S[keep]] = base[S[keep]]
            b[t] = v
        out.append(Candidate(rng.normal(scale=0.5, size=K), b))
    return out


def treaties(n_candidates: int, K: int, seed: int, d: int = 5,
             live_prob: float = 0.7) -> list[Candidate]:
    """Excess-of-loss treaties over peril subsets with quota shares."""
    rng = np.random.default_rng(seed)
    out = []
    for _ in range(n_candidates):
        msz = rng.integers(1, d + 1)
        S = rng.choice(d, size=msz, replace=False)
        share = rng.uniform(0.3, 1.0, size=msz)
        base = np.zeros(d); base[S] = share
        b = np.zeros((K, d))
        for t in range(K):
            live = rng.random(msz) < live_prob
            v = np.zeros(d); v[S[live]] = base[S[live]]
            b[t] = v
        out.append(Candidate(rng.normal(scale=0.05, size=K), b))
    return out
